-- FIRST handle container DB
-- TEMP Tablespace
CREATE TEMPORARY TABLESPACE TEMP2 TEMPFILE 
  '/u01/app/oracle/oradata/cdb12/temp2_01.dbf' SIZE 5M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;

alter database default temporary tablespace TEMP2;


-- UNDO Tablespace 
CREATE UNDO TABLESPACE UNDOTBS2 DATAFILE 
  '/u01/app/oracle/oradata/cdb12/undotbs2_01.dbf' SIZE 5M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
RETENTION NOGUARANTEE
BLOCKSIZE 8K
FLASHBACK ON;

ALTER SYSTEM SET UNDO_TABLESPACE = UNDOTBS2;

DROP TABLESPACE UNDOTBS1 INCLUDING CONTENTS AND DATAFILES;

CREATE UNDO TABLESPACE UNDOTBS1 DATAFILE 
  '/u01/app/oracle/oradata/cdb12/undotbs_01.dbf' SIZE 5M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
RETENTION NOGUARANTEE
BLOCKSIZE 8K
FLASHBACK ON;

ALTER SYSTEM SET UNDO_TABLESPACE = UNDOTBS1;

DROP TABLESPACE UNDOTBS2 INCLUDING CONTENTS AND DATAFILES;

-- Then to ORCL pluggable DB
ALTER SESSION SET CONTAINER = ORCL ;

ALTER DATABASE 
  DATAFILE '/u01/app/oracle/oradata/cdb12/orcl/app_data01.dbf'
 RESIZE 5M;
ALTER DATABASE 
  DATAFILE '/u01/app/oracle/oradata/cdb12/orcl/app_data01.dbf'
  AUTOEXTEND ON
  NEXT 8M
  MAXSIZE UNLIMITED;

ALTER DATABASE 
  DATAFILE '/u01/app/oracle/oradata/cdb12/orcl/app_idx01.dbf'
 RESIZE 5M;
ALTER DATABASE 
  DATAFILE '/u01/app/oracle/oradata/cdb12/orcl/app_idx01.dbf'
  AUTOEXTEND ON
  NEXT 8M
  MAXSIZE UNLIMITED;

ALTER DATABASE 
  DATAFILE '/u01/app/oracle/oradata/cdb12/orcl/app_lobs01.dbf'
 RESIZE 5M;
ALTER DATABASE 
  DATAFILE '/u01/app/oracle/oradata/cdb12/orcl/app_lobs01.dbf'
  AUTOEXTEND ON
  NEXT 8M
  MAXSIZE UNLIMITED;

exit
